export default [
  { id: "11", title: "Дело 1" },
  { id: "12", title: "Дело 2" },
  { id: "13", title: "Дело 3" },
  { id: "14", title: "Дело 4" },
  { id: "15", title: "Дело 5" },
  { id: "16", title: "Дело 6" },
  { id: "17", title: "Дело 7" },
  { id: "18", title: "Дело 8" },
  { id: "19", title: "Дело 9" },
  { id: "20", title: "Дело 10" },
  { id: "21", title: "Дело 11" },
  { id: "22", title: "Дело 12" },
  { id: "23", title: "Дело 13" },
  { id: "24", title: "Дело 14" },
  { id: "25", title: "Дело 15" },
];
